// src/components/Widget/Picture.vue
<script setup lang="ts">
  import { IComponent } from '../../types'

  const props = defineProps<{
    element: IComponent
  }>()
</script>

<template>
  <div class="image-wrap">
    <img class="image" :src="props.element.propValue" alt="" />
  </div>
</template>

<style lang="scss" scoped>
  .image {
    width: 100%;
    height: 100%;
  }
</style>

// packages/react/src/components/Widget/Picture.tsx
import { getWidgetStyle } from './util'
const Picture = ({ propValue, styles }) => {
  const newStyles = getWidgetStyle(styles)
  return (
    <div className="image-wrapper" style={newStyles}>
      <img
        style={{ ...newStyles, width: '100%', height: '100%' }}
        src={propValue}
        alt=""
      />
    </div>
  )
}

export default Picture
