// packages/web/src/components/elements/Picture.vue
<script setup lang="ts">
  import { IComponent } from '../../types'

  const props = defineProps<{
    element: IComponent
  }>()
</script>

<template>
  <div class="base-element-image" :style="{ ...props.element.style }">
    <div
      class="element-rotate"
      :style="{ transform: `rotate(${props.element.style.rotate}deg)` }"
    >
      <div class="element-content">
        <img class="image" :src="props.element.propValue" alt="" />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
  .image {
    width: 100%;
    height: 100%;
  }
</style>

// packages/react/src/components/Widget/Picture.tsx
import { getWidgetStyle } from './util'
const Picture = ({ propValue, styles }) => {
  const newStyles = getWidgetStyle(styles)
  return (
    <div className="image-wrapper" style={newStyles}>
      <img
        style={{ ...newStyles, width: '100%', height: '100%' }}
        src={propValue}
        alt=""
      />
    </div>
  )
}

export default Picture
